apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-appset
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - app: app1
            appns: app1

  template:
    metadata:
      name: '{{app}}'

    spec:
      project: doc

      source:
        repoURL: https://github.com/ferchdav/argocd-example-apps
        path: app
        targetRevision: master

      destination:
        name: in-cluster
        namespace: '{{appns}}'

      syncPolicy:
        automated:
          selfHeal: true
          prune: true

        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
